### ISSUE TITLE
[FEAT] Keytool – multiple passkeys for the same username

### ISSUE THREAD

**Issue by egregors** [egregors/passkey#3]
# Keytool

One of the most non-trivial problem with a passkey is how to implement several passkeys associated with the same user. 

## Why? 

In modern world, you want to access to your data from different devices. In this case, the situation when you can use only One-to-One pair username ↔ passkey is pretty frustrating. I want to make simple enough but still strongly secure way to bind N+1 passkeys with the same user.

## How? 

In general, the idea is pretty straight forward: the user, which is already logged in, will get the ability to add the new passkey to his current account. To do that, we will generate unique token | link | qr-code, which should be opened from other device | WebAuthn provider. 

> [!NOTE]
> TODO: add principal schema

## TODO

- [ ] add secret token storage interface (it may be optional)
  - [ ] will it be default feature or feature added by Options? idk
- [ ] add new API route to prove token, smth like `/api/add_key`
- [ ] update session store to work with multiple sesstion per user
- [ ] update _example app
  - [ ] impl secret token storage interface
  - [ ] maybe add separated README for _example?
  - [ ] add demo gif (ppl like demo vids)
- [ ] update README

**Comment by egregors** [comment]
Just for now, I'm not really sure. I want to believe it wouldn't be a huge problem to support Linux here. As far as I know, popular browsers partially support WebAuthn (at least Firefox). I want to check how 1Password for Linux deals with passkeys as well.

The idea of `Keytool` here is supposed to be key-provider-agnostic. You log in with device A, which has a public key associated with the user Alice. Next, you generate a one-time “invite” to add another device and bind it with the same user. At this point, I should be able to use any WebAuthn-supported device to perform the “registration” procedure, but within the context of the invite. We put the second device's credentials into the same `User.Creds` store. The next time Alice tries to log in, we just look over all the already stored credentials.

It sounds pretty simple, but I still need to try to implement a proof-of-concept. How we already a bit dessuced in another #9 issue, there is a [WebAuthn.BeginDiscoverableLogin](https://pkg.go.dev/github.com/go-webauthn/webauthn@v0.10.2/webauthn#WebAuthn.BeginDiscoverableLogin) stuff already presented in the underlying library. 

In any case, I'll track the progress of all this stuff in this issue.

**Comment by egregors** [comment]
@gedw99, thanks for the references! To be honest, I was thinking about the concept of “Device X is attempting to log in, please approve or deny it” as an additional security layer. I mean, you could first generate a QR code to add a new device, and then approve (or deny) it from the first one. Last time, I decided it might be a bit of an overhead. But now, I’m reconsidering :)

It actually sounds pretty cool. It could be an optional feature for keytool. A bit less convenient, but much more secure. I’ll add it to the keytool “roadmap.” By the way, NATS looks huuuuge. I have to find time to play around with it. Anyway, let’s take it step by step. :)
